# Generated by Django 4.2.2 on 2023-08-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0002_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='main_genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies_api.genre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='other_genres', to='movies_api.genre'),
        ),
    ]
